#!/usr/bin/env bash
set -euo pipefail

# Configure helper for the pacto-dev-env Claude Code skill.
# Run from a Pacto sibling repo to write local dev configuration.

PACTO_DEV_ENV_DIR="${PACTO_DEV_ENV_DIR:-}"

if [[ -z "$PACTO_DEV_ENV_DIR" ]]; then
  # Try to infer from the directory layout (sibling of current repo)
  PACTO_DEV_ENV_DIR="$(cd "$(dirname "$0")/.." && pwd)"
fi

if [[ ! -f "$PACTO_DEV_ENV_DIR/scripts/pacto-connect.sh" ]]; then
  echo "[configure] Cannot find pacto-dev-env at $PACTO_DEV_ENV_DIR"
  echo "[configure] Set PACTO_DEV_ENV_DIR to the correct path and retry."
  exit 1
fi

CURRENT_REPO_DIR="$(pwd)"
CURRENT_REPO_NAME="$(basename "$CURRENT_REPO_DIR")"

# Prefer git remote name, fall back to directory name
detect_repo() {
  local remote
  remote="$(git -C "$CURRENT_REPO_DIR" remote get-url origin 2>/dev/null || true)"
  if [[ -n "$remote" ]]; then
    basename "$remote" .git
  else
    echo "$CURRENT_REPO_NAME"
  fi
}

REPO_NAME="$(detect_repo)"

HOST_RELAY_WSS_PORT=7001
HOST_ANVIL_HTTPS_PORT=8546
HOST_AZTEC_HTTPS_PORT=8445
HOST_BUNKER_HTTPS_PORT=8446

generate_env_block() {
  cat <<EOF
# Pacto local dev environment settings
# Generated by the pacto-dev-env skill. Do not commit real secrets.
PACTO_RELAY_URL=wss://localhost:${HOST_RELAY_WSS_PORT}
PACTO_RPC_URL=https://localhost:${HOST_ANVIL_HTTPS_PORT}
PACTO_CHAIN_ID=31337
PACTO_BOT_API_SOCKET=/var/lib/pacto-bot-api/pacto-bot-api.sock
PACTO_AZTEC_RPC_URL=https://localhost:${HOST_AZTEC_HTTPS_PORT}
PACTO_BUNKER_URL=https://localhost:${HOST_BUNKER_HTTPS_PORT}
EOF
}

write_env_file() {
  local env_file="$CURRENT_REPO_DIR/.env"
  if [[ -f "$env_file" ]]; then
    echo "[configure] $env_file already exists. Printing values below; merge manually."
    generate_env_block
    return
  fi

  echo "[configure] Writing $env_file..."
  generate_env_block > "$env_file"
  echo "[configure] Done."
}

configure_pacto_app() {
  echo "[configure] Configuring pacto-app..."
  write_env_file
  echo
  echo "[configure] Add these settings in the Pacto app:"
  echo "  Nostr relay: wss://localhost:${HOST_RELAY_WSS_PORT}"
  echo "  EVM RPC:     https://localhost:${HOST_ANVIL_HTTPS_PORT} (chain 31337)"
  echo "  If using self-signed Caddy certs, trust the CA or skip TLS verification."
}

configure_pacto_gov() {
  echo "[configure] Configuring pacto-gov..."
  write_env_file
  echo
  echo "[configure] Foundry usage:"
  echo "  forge script script/Deploy.s.sol --rpc-url https://localhost:${HOST_ANVIL_HTTPS_PORT} --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
}

configure_pacto_bot_api() {
  echo "[configure] Configuring pacto-bot-api..."
  write_env_file
  echo
  echo "[configure] Generate the daemon config in pacto-dev-env:"
  echo "  cd \$(PACTO_DEV_ENV_DIR) && ./scripts/init-pacto-bot-api-config.sh"
  echo "[configure] Add bot identities with pacto-bot-admin."
}

configure_pacto_aztec() {
  echo "[configure] Configuring pacto-aztec..."
  write_env_file
  echo
  echo "[configure] Aztec RPC: https://localhost:${HOST_AZTEC_HTTPS_PORT}"
}

case "$REPO_NAME" in
  pacto-app)
    configure_pacto_app
    ;;
  pacto-gov)
    configure_pacto_gov
    ;;
  pacto-bot-api)
    configure_pacto_bot_api
    ;;
  pacto-aztec)
    configure_pacto_aztec
    ;;
  *)
    echo "[configure] Unknown repo '$REPO_NAME'. Printing generic environment variables:"
    generate_env_block
    ;;
esac

# Always print the live connection block from the dev environment
if [[ -x "$PACTO_DEV_ENV_DIR/scripts/pacto-connect.sh" ]]; then
  echo
  echo "[configure] Live connection info from pacto-dev-env:"
  "$PACTO_DEV_ENV_DIR/scripts/pacto-connect.sh"
fi
